services:
  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    volumes:
      - .:/app
    ports:
      - 8001:8001
    depends_on:
      - db

    networks:
      - wheatwise-network
    # env_file: 
    #   - .env 

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - wheatwise-network
    # env_file: 
    #   - .env 

volumes:
  postgres_data:

networks:
  wheatwise-network:




# services:
#   fastapi:
#     build: .
#     command: uvicorn app.main:app --host 0.0.0.0 --port 8001
#     volumes:
#       - .:/app
#     ports:
#       - 8001:8001
#     depends_on:
#       - db
#     environment:
#       PROFILE_FOLDER_PATH: /app/app/static/uploads/profiles
#       UPLOAD_FOLDER_PATH: /app/app/static/uploads/images
#       MODEL_PATH: /app/app/static/weights/efficientnet_b0_scripted.pt
#       PROFILE_PATH: /app/app/static/uploads/profiles/profile-image.jpg
#       DATABASE_HOST: db
#     networks:
#       - wheatwise-network
#     # env_file: 
#     #   - .env 

#   db:
#     image: postgres:16-alpine
#     restart: always
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       POSTGRES_USER: ${DATABASE_USERNAME}
#       POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#       POSTGRES_DB: ${APP_DATABASE}
#     ports:
#       - 5432:5432
#     networks:
#       - wheatwise-network
#     # env_file: 
#     #   - .env 

# volumes:
#   postgres_data:

# networks:
#   wheatwise-network:
